### ISSUE TITLE
modulize headers

### ISSUE THREAD

**Issue by winstonallo** [42-projects-abied-ch/webserv#17]
rn there is only one general header for all files, would be better for each file to include only needed headers - it got lost in the merging somehow probably my bad

**Comment by winstonallo** [comment]
- [x] Utils namespace
- [x] Config class
- [x] Director class
- [x] LocationInfo class
- [x] Log namespace
- [x] Node class
- [x] ServerInfo class

**Comment by spirogio** [comment]
did server handler includes. they have their own headers now.
